spring.application.name=warehouse

spring.datasource.url=jdbc:mysql://localhost:3306/warehouse?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
# spring.profiles.active=local

app.default-warehouse-id=b0a2f673-5902-4b62-91d2-cf5153876fbd

# JWT ?????????
security.jwt.security-key=JbVg3jLDLg3R1z4gVo0kZg8gWtzmrO9fFQdD6fO7kWc=
security.jwt.expiration-time=86400000 



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080